(* File generated by the BNF Converter (bnfc 2.9.5). *)

type binary = Binary of string
and stmtLines =
   StmtLinesStmt of stmt

and stmt =
   Stmt_Assign of lexpr * expr
 | Stmt_ConstDecl of typeT * string * expr
 | Stmt_VarDecl of typeT * string * expr
 | Stmt_VarDeclsNoInit of typeT * string list
 | Stmt_Assert of expr
 | Stmt_Throw of string
 | Stmt_TCall of callName * int list * expr list
 | Stmt_If of expr * stmt list * stmt list

and regTypeSlices =
   Slice_HiLo of expr

and typeT =
   Type_Bits of int
 | Type_Boolean
 | Type_Constructor of string

and lexpr =
   Lexpr_KnownVar of varName
 | Lexpr_LocalVar of string
 | Lexpr_Field of structName * structField
 | Lexpr_Array of arrayName * int

and expr =
   Expr_True
 | Expr_False
 | Expr_KnownVar of varName
 | Expr_LocalVar of string
 | Expr_Prim of primName * int list * expr list
 | Expr_VecPrim of vecPrimName * int list * expr list
 | Expr_Slices of expr * slice
 | Expr_Field of structName * structField
 | Expr_Array of arrayName * int
 | Expr_LitInt of int
 | Expr_LitBits of binary

and slice =
   Slice_LoWd of int * int

and varName =
   Var_PC
 | Var_SP_EL0
 | Var_FPCR
 | Var_FPSR
 | Var_BTypeCompatible
 | Var_BranchTaken
 | Var_BTypeNext
 | Var_ExclusiveLocal

and structName =
   Struct_Pstate

and structField =
   Field_N
 | Field_Z
 | Field_C
 | Field_V
 | Field_A
 | Field_D
 | Field_DIT
 | Field_F
 | Field_I
 | Field_PAN
 | Field_SP
 | Field_SSBS
 | Field_TCO
 | Field_UAO
 | Field_BTYPE

and arrayName =
   Array_R
 | Array_Z

and callName =
   Call_Mem_set
 | Call_AtomicStart
 | Call_AtomicEnd
 | Call_Memtag_read
 | Call_Memtag_set

and primName =
   Prim_Mem_read
 | Prim_and_bool
 | Prim_or_bool
 | Prim_not_bool
 | Prim_cvt_bits_uint
 | Prim_eq_bits
 | Prim_ne_bits
 | Prim_not_bits
 | Prim_cvt_bool_bv
 | Prim_or_bits
 | Prim_eor_bits
 | Prim_and_bits
 | Prim_add_bits
 | Prim_sub_bits
 | Prim_sdiv_bits
 | Prim_sle_bits
 | Prim_slt_bits
 | Prim_mul_bits
 | Prim_append_bits
 | Prim_lsr_bits
 | Prim_lsl_bits
 | Prim_asr_bits
 | Prim_replicate_bits
 | Prim_ZeroExtend
 | Prim_SignExtend
 | Prim_FPCompare
 | Prim_FPCompareEQ
 | Prim_FPCompareGE
 | Prim_FPCompareGT
 | Prim_FPAdd
 | Prim_FPSub
 | Prim_FPMulAdd
 | Prim_FPMulAddH
 | Prim_FPMulX
 | Prim_FPMul
 | Prim_FPDiv
 | Prim_FPMin
 | Prim_FPMinNum
 | Prim_FPMax
 | Prim_FPMaxNum
 | Prim_FPRecpX
 | Prim_FPSqrt
 | Prim_FPRecipEstimate
 | Prim_UnsignedRSqrtEstimate
 | Prim_FPRSqrtEstimate
 | Prim_BFAdd
 | Prim_BFMul
 | Prim_FPConvertBF
 | Prim_FPRecipStepFused
 | Prim_FPRSqrtStepFused
 | Prim_FPToFixed
 | Prim_FixedToFP
 | Prim_FPConvert
 | Prim_FPRoundInt
 | Prim_FPRoundIntN
 | Prim_FPToFixedJS_impl

and vecPrimName =
   VecPrim_Elem_set
 | VecPrim_Elem_read
 | VecPrim_add_vec
 | VecPrim_sub_vec
 | VecPrim_mul_vec
 | VecPrim_sdiv_vec
 | VecPrim_lsr_vec
 | VecPrim_asr_vec
 | VecPrim_lsl_vec
 | VecPrim_ite_vec
 | VecPrim_sle_vec
 | VecPrim_slt_vec
 | VecPrim_eq_vec
 | VecPrim_zcast_vec
 | VecPrim_scast_vec
 | VecPrim_trunc_vec
 | VecPrim_select_vec
 | VecPrim_shuffle_vec
 | VecPrim_reduce_add

