(* File generated by the BNF Converter (bnfc 2.9.5). *)

open Lexing

(* this should really be in the parser, but ocamlyacc won't put it in the .mli *)
exception Parse_error of Lexing.position * Lexing.position
