/* File generated by the BNF Converter (bnfc 2.9.5). */

/* Parser definition for use with menhir */

%{
open AbsSemantics
open Lexing
%}

%token KW_Stmt_Assign KW_Stmt_ConstDecl KW_Stmt_VarDecl KW_Stmt_VarDeclsNoInit KW_Stmt_Assert KW_Stmt_Throw KW_Stmt_TCall KW_Stmt_If KW_Slice_HiLo KW_Type_Bits KW_Type_Constructor KW_LExpr_Var KW_LExpr_Field KW_LExpr_Array KW_Expr_Var KW_Expr_TApply KW_Expr_Slices KW_Expr_Field KW_Expr_Array KW_Slice_LoWd

%token SYMB1 /* ; */
%token SYMB2 /* ( */
%token SYMB3 /* , */
%token SYMB4 /* ) */
%token SYMB5 /* [ */
%token SYMB6 /* ] */
%token SYMB7 /* "boolean" */
%token SYMB8 /* "TRUE" */
%token SYMB9 /* "FALSE" */
%token SYMB10 /* "_PC" */
%token SYMB11 /* "SP_EL0" */
%token SYMB12 /* "FPCR" */
%token SYMB13 /* "FPSR" */
%token SYMB14 /* "BTypeCompatible" */
%token SYMB15 /* "__BranchTaken" */
%token SYMB16 /* "BTypeNext" */
%token SYMB17 /* "__ExclusiveLocal" */
%token SYMB18 /* "PSTATE" */
%token SYMB19 /* "N" */
%token SYMB20 /* "Z" */
%token SYMB21 /* "C" */
%token SYMB22 /* "V" */
%token SYMB23 /* "A" */
%token SYMB24 /* "D" */
%token SYMB25 /* "DIT" */
%token SYMB26 /* "F" */
%token SYMB27 /* "I" */
%token SYMB28 /* "PAN" */
%token SYMB29 /* "SP" */
%token SYMB30 /* "SSBS" */
%token SYMB31 /* "TCO" */
%token SYMB32 /* "UAO" */
%token SYMB33 /* "BTYPE" */
%token SYMB34 /* "_R" */
%token SYMB35 /* "_Z" */
%token SYMB36 /* "Mem.set.0" */
%token SYMB37 /* "AtomicStart.0" */
%token SYMB38 /* "AtomicEnd.0" */
%token SYMB39 /* "AArch64.MemTag.read.0" */
%token SYMB40 /* "AArch64.MemTag.set.0" */
%token SYMB41 /* "Mem.read.0" */
%token SYMB42 /* "and_bool.0" */
%token SYMB43 /* "or_bool.0" */
%token SYMB44 /* "not_bool.0" */
%token SYMB45 /* "cvt_bits_uint.0" */
%token SYMB46 /* "eq_bits.0" */
%token SYMB47 /* "ne_bits.0" */
%token SYMB48 /* "not_bits.0" */
%token SYMB49 /* "cvt_bool_bv.0" */
%token SYMB50 /* "or_bits.0" */
%token SYMB51 /* "eor_bits.0" */
%token SYMB52 /* "and_bits.0" */
%token SYMB53 /* "add_bits.0" */
%token SYMB54 /* "sub_bits.0" */
%token SYMB55 /* "sdiv_bits.0" */
%token SYMB56 /* "sle_bits.0" */
%token SYMB57 /* "slt_bits.0" */
%token SYMB58 /* "mul_bits.0" */
%token SYMB59 /* "append_bits.0" */
%token SYMB60 /* "lsr_bits.0" */
%token SYMB61 /* "lsl_bits.0" */
%token SYMB62 /* "asr_bits.0" */
%token SYMB63 /* "replicate_bits.0" */
%token SYMB64 /* "ZeroExtend.0" */
%token SYMB65 /* "SignExtend.0" */
%token SYMB66 /* "FPCompare.0" */
%token SYMB67 /* "FPCompareEQ.0" */
%token SYMB68 /* "FPCompareGE.0" */
%token SYMB69 /* "FPCompareGT.0" */
%token SYMB70 /* "FPAdd.0" */
%token SYMB71 /* "FPSub.0" */
%token SYMB72 /* "FPMulAdd.0" */
%token SYMB73 /* "FPMulAddH.0" */
%token SYMB74 /* "FPMulX.0" */
%token SYMB75 /* "FPMul.0" */
%token SYMB76 /* "FPDiv.0" */
%token SYMB77 /* "FPMin.0" */
%token SYMB78 /* "FPMinNum.0" */
%token SYMB79 /* "FPMax.0" */
%token SYMB80 /* "FPMaxNum.0" */
%token SYMB81 /* "FPRecpX.0" */
%token SYMB82 /* "FPSqrt.0" */
%token SYMB83 /* "FPRecipEstimate.0" */
%token SYMB84 /* "UnsignedRSqrtEstimate.0" */
%token SYMB85 /* "FPRSqrtEstimate.0" */
%token SYMB86 /* "BFAdd.0" */
%token SYMB87 /* "BFMul.0" */
%token SYMB88 /* "FPConvertBF.0" */
%token SYMB89 /* "FPRecipStepFused.0" */
%token SYMB90 /* "FPRSqrtStepFused.0" */
%token SYMB91 /* "FPToFixed.0" */
%token SYMB92 /* "FixedToFP.0" */
%token SYMB93 /* "FPConvert.0" */
%token SYMB94 /* "FPRoundInt.0" */
%token SYMB95 /* "FPRoundIntN.0" */
%token SYMB96 /* "FPToFixedJS_impl.0" */
%token SYMB97 /* "Elem.set.0" */
%token SYMB98 /* "Elem.read.0" */
%token SYMB99 /* "add_vec.0" */
%token SYMB100 /* "sub_vec.0" */
%token SYMB101 /* "mul_vec.0" */
%token SYMB102 /* "sdiv_vec.0" */
%token SYMB103 /* "lsr_vec.0" */
%token SYMB104 /* "asr_vec.0" */
%token SYMB105 /* "lsl_vec.0" */
%token SYMB106 /* "ite_vec.0" */
%token SYMB107 /* "sle_vec.0" */
%token SYMB108 /* "slt_vec.0" */
%token SYMB109 /* "eq_vec.0" */
%token SYMB110 /* "zcast_vec.0" */
%token SYMB111 /* "scast_vec.0" */
%token SYMB112 /* "trunc_vec.0" */
%token SYMB113 /* "select_vec.0" */
%token SYMB114 /* "shuffle_vec.0" */
%token SYMB115 /* "reduce_add.0" */

%token TOK_EOF
%token <string> TOK_Ident
%token <char>   TOK_Char
%token <float>  TOK_Double
%token <int>    TOK_Integer
%token <string> TOK_String
%token <string> TOK_Binary

%start pStmtLines_list
%type <AbsSemantics.stmtLines list> pStmtLines_list

%type <AbsSemantics.stmt list> stmt_list
%type <string list> string_list
%type <AbsSemantics.stmtLines list> stmtLines_list
%type <AbsSemantics.stmtLines> stmtLines
%type <AbsSemantics.stmt> stmt
%type <AbsSemantics.regTypeSlices list> regTypeSlices_list
%type <AbsSemantics.regTypeSlices> regTypeSlices
%type <AbsSemantics.typeT> typeT
%type <AbsSemantics.lexpr> lexpr
%type <int list> int_list
%type <AbsSemantics.expr list> expr_list
%type <AbsSemantics.expr> expr
%type <AbsSemantics.slice> slice
%type <AbsSemantics.varName> varName
%type <AbsSemantics.structName> structName
%type <AbsSemantics.structField> structField
%type <AbsSemantics.arrayName> arrayName
%type <AbsSemantics.callName> callName
%type <AbsSemantics.primName> primName
%type <AbsSemantics.vecPrimName> vecPrimName

%type <int> int
%type <string> string
%type <AbsSemantics.binary> binary

%%

pStmtLines_list : stmtLines_list TOK_EOF { $1 };

stmt_list : /* empty */ { []  }
  | stmt { (fun x -> [x]) $1 }
  | stmt SYMB1 stmt_list { (fun (x,xs) -> x::xs) ($1, $3) }
  ;

string_list : /* empty */ { []  }
  | string { (fun x -> [x]) $1 }
  | string SYMB1 string_list { (fun (x,xs) -> x::xs) ($1, $3) }
  ;

stmtLines_list : /* empty */ { []  }
  | stmtLines stmtLines_list { (fun (x,xs) -> x::xs) ($1, $2) }
  ;

stmtLines : stmt { StmtLinesStmt $1 }
  ;

stmt : KW_Stmt_Assign SYMB2 lexpr SYMB3 expr SYMB4 { Stmt_Assign ($3, $5) }
  | KW_Stmt_ConstDecl SYMB2 typeT SYMB3 string SYMB3 expr SYMB4 { Stmt_ConstDecl ($3, $5, $7) }
  | KW_Stmt_VarDecl SYMB2 typeT SYMB3 string SYMB3 expr SYMB4 { Stmt_VarDecl ($3, $5, $7) }
  | KW_Stmt_VarDeclsNoInit SYMB2 typeT SYMB3 SYMB5 string_list SYMB6 SYMB4 { Stmt_VarDeclsNoInit ($3, $6) }
  | KW_Stmt_Assert SYMB2 expr SYMB4 { Stmt_Assert $3 }
  | KW_Stmt_Throw SYMB2 string SYMB4 { Stmt_Throw $3 }
  | KW_Stmt_TCall SYMB2 callName SYMB3 SYMB5 int_list SYMB6 SYMB3 SYMB5 expr_list SYMB6 SYMB4 { Stmt_TCall ($3, $6, $10) }
  | KW_Stmt_If SYMB2 expr SYMB3 SYMB5 stmt_list SYMB6 SYMB3 SYMB5 SYMB6 SYMB3 SYMB5 stmt_list SYMB6 SYMB4 { Stmt_If ($3, $6, $13) }
  ;

regTypeSlices_list : regTypeSlices { (fun x -> [x]) $1 }
  | regTypeSlices SYMB3 regTypeSlices_list { (fun (x,xs) -> x::xs) ($1, $3) }
  ;

regTypeSlices : SYMB2 SYMB5 KW_Slice_HiLo SYMB2 expr SYMB3 { Slice_HiLo $5 }
  ;

typeT : KW_Type_Bits SYMB2 int SYMB4 { Type_Bits $3 }
  | KW_Type_Constructor SYMB2 SYMB7 SYMB4 { Type_Boolean  }
  | KW_Type_Constructor SYMB2 string SYMB4 { Type_Constructor $3 }
  ;

lexpr : KW_LExpr_Var SYMB2 varName SYMB4 { Lexpr_KnownVar $3 }
  | KW_LExpr_Var SYMB2 string SYMB4 { Lexpr_LocalVar $3 }
  | KW_LExpr_Field SYMB2 KW_LExpr_Var SYMB2 structName SYMB4 SYMB3 structField SYMB4 { Lexpr_Field ($5, $8) }
  | KW_LExpr_Array SYMB2 KW_LExpr_Var SYMB2 arrayName SYMB4 SYMB3 int SYMB4 { Lexpr_Array ($5, $8) }
  ;

int_list : /* empty */ { []  }
  | int { (fun x -> [x]) $1 }
  | int SYMB1 int_list { (fun (x,xs) -> x::xs) ($1, $3) }
  ;

expr_list : /* empty */ { []  }
  | expr { (fun x -> [x]) $1 }
  | expr SYMB1 expr_list { (fun (x,xs) -> x::xs) ($1, $3) }
  ;

expr : KW_Expr_Var SYMB2 SYMB8 SYMB4 { Expr_True  }
  | KW_Expr_Var SYMB2 SYMB9 SYMB4 { Expr_False  }
  | KW_Expr_Var SYMB2 varName SYMB4 { Expr_KnownVar $3 }
  | KW_Expr_Var SYMB2 string SYMB4 { Expr_LocalVar $3 }
  | KW_Expr_TApply SYMB2 primName SYMB3 SYMB5 int_list SYMB6 SYMB3 SYMB5 expr_list SYMB6 SYMB4 { Expr_Prim ($3, $6, $10) }
  | KW_Expr_TApply SYMB2 vecPrimName SYMB3 SYMB5 int_list SYMB6 SYMB3 SYMB5 expr_list SYMB6 SYMB4 { Expr_VecPrim ($3, $6, $10) }
  | KW_Expr_Slices SYMB2 expr SYMB3 SYMB5 slice SYMB6 SYMB4 { Expr_Slices ($3, $6) }
  | KW_Expr_Field SYMB2 KW_Expr_Var SYMB2 structName SYMB4 SYMB3 structField SYMB4 { Expr_Field ($5, $8) }
  | KW_Expr_Array SYMB2 KW_Expr_Var SYMB2 arrayName SYMB4 SYMB3 int SYMB4 { Expr_Array ($5, $8) }
  | int { Expr_LitInt $1 }
  | binary { Expr_LitBits $1 }
  | SYMB2 expr SYMB4 {  $2 }
  ;

slice : KW_Slice_LoWd SYMB2 int SYMB3 int SYMB4 { Slice_LoWd ($3, $5) }
  ;

varName : SYMB10 { Var_PC  }
  | SYMB11 { Var_SP_EL0  }
  | SYMB12 { Var_FPCR  }
  | SYMB13 { Var_FPSR  }
  | SYMB14 { Var_BTypeCompatible  }
  | SYMB15 { Var_BranchTaken  }
  | SYMB16 { Var_BTypeNext  }
  | SYMB17 { Var_ExclusiveLocal  }
  ;

structName : SYMB18 { Struct_Pstate  }
  ;

structField : SYMB19 { Field_N  }
  | SYMB20 { Field_Z  }
  | SYMB21 { Field_C  }
  | SYMB22 { Field_V  }
  | SYMB23 { Field_A  }
  | SYMB24 { Field_D  }
  | SYMB25 { Field_DIT  }
  | SYMB26 { Field_F  }
  | SYMB27 { Field_I  }
  | SYMB28 { Field_PAN  }
  | SYMB29 { Field_SP  }
  | SYMB30 { Field_SSBS  }
  | SYMB31 { Field_TCO  }
  | SYMB32 { Field_UAO  }
  | SYMB33 { Field_BTYPE  }
  ;

arrayName : SYMB34 { Array_R  }
  | SYMB35 { Array_Z  }
  ;

callName : SYMB36 { Call_Mem_set  }
  | SYMB37 { Call_AtomicStart  }
  | SYMB38 { Call_AtomicEnd  }
  | SYMB39 { Call_Memtag_read  }
  | SYMB40 { Call_Memtag_set  }
  ;

primName : SYMB41 { Prim_Mem_read  }
  | SYMB42 { Prim_and_bool  }
  | SYMB43 { Prim_or_bool  }
  | SYMB44 { Prim_not_bool  }
  | SYMB45 { Prim_cvt_bits_uint  }
  | SYMB46 { Prim_eq_bits  }
  | SYMB47 { Prim_ne_bits  }
  | SYMB48 { Prim_not_bits  }
  | SYMB49 { Prim_cvt_bool_bv  }
  | SYMB50 { Prim_or_bits  }
  | SYMB51 { Prim_eor_bits  }
  | SYMB52 { Prim_and_bits  }
  | SYMB53 { Prim_add_bits  }
  | SYMB54 { Prim_sub_bits  }
  | SYMB55 { Prim_sdiv_bits  }
  | SYMB56 { Prim_sle_bits  }
  | SYMB57 { Prim_slt_bits  }
  | SYMB58 { Prim_mul_bits  }
  | SYMB59 { Prim_append_bits  }
  | SYMB60 { Prim_lsr_bits  }
  | SYMB61 { Prim_lsl_bits  }
  | SYMB62 { Prim_asr_bits  }
  | SYMB63 { Prim_replicate_bits  }
  | SYMB64 { Prim_ZeroExtend  }
  | SYMB65 { Prim_SignExtend  }
  | SYMB66 { Prim_FPCompare  }
  | SYMB67 { Prim_FPCompareEQ  }
  | SYMB68 { Prim_FPCompareGE  }
  | SYMB69 { Prim_FPCompareGT  }
  | SYMB70 { Prim_FPAdd  }
  | SYMB71 { Prim_FPSub  }
  | SYMB72 { Prim_FPMulAdd  }
  | SYMB73 { Prim_FPMulAddH  }
  | SYMB74 { Prim_FPMulX  }
  | SYMB75 { Prim_FPMul  }
  | SYMB76 { Prim_FPDiv  }
  | SYMB77 { Prim_FPMin  }
  | SYMB78 { Prim_FPMinNum  }
  | SYMB79 { Prim_FPMax  }
  | SYMB80 { Prim_FPMaxNum  }
  | SYMB81 { Prim_FPRecpX  }
  | SYMB82 { Prim_FPSqrt  }
  | SYMB83 { Prim_FPRecipEstimate  }
  | SYMB84 { Prim_UnsignedRSqrtEstimate  }
  | SYMB85 { Prim_FPRSqrtEstimate  }
  | SYMB86 { Prim_BFAdd  }
  | SYMB87 { Prim_BFMul  }
  | SYMB88 { Prim_FPConvertBF  }
  | SYMB89 { Prim_FPRecipStepFused  }
  | SYMB90 { Prim_FPRSqrtStepFused  }
  | SYMB91 { Prim_FPToFixed  }
  | SYMB92 { Prim_FixedToFP  }
  | SYMB93 { Prim_FPConvert  }
  | SYMB94 { Prim_FPRoundInt  }
  | SYMB95 { Prim_FPRoundIntN  }
  | SYMB96 { Prim_FPToFixedJS_impl  }
  ;

vecPrimName : SYMB97 { VecPrim_Elem_set  }
  | SYMB98 { VecPrim_Elem_read  }
  | SYMB99 { VecPrim_add_vec  }
  | SYMB100 { VecPrim_sub_vec  }
  | SYMB101 { VecPrim_mul_vec  }
  | SYMB102 { VecPrim_sdiv_vec  }
  | SYMB103 { VecPrim_lsr_vec  }
  | SYMB104 { VecPrim_asr_vec  }
  | SYMB105 { VecPrim_lsl_vec  }
  | SYMB106 { VecPrim_ite_vec  }
  | SYMB107 { VecPrim_sle_vec  }
  | SYMB108 { VecPrim_slt_vec  }
  | SYMB109 { VecPrim_eq_vec  }
  | SYMB110 { VecPrim_zcast_vec  }
  | SYMB111 { VecPrim_scast_vec  }
  | SYMB112 { VecPrim_trunc_vec  }
  | SYMB113 { VecPrim_select_vec  }
  | SYMB114 { VecPrim_shuffle_vec  }
  | SYMB115 { VecPrim_reduce_add  }
  ;

int :  TOK_Integer  { $1 };
string : TOK_String { $1 };
binary : TOK_Binary { Binary ($1)};

