(* File generated by the BNF Converter (bnfc 2.9.5). *)

(* pretty-printer *)

open Printf

(* We use string buffers for efficient string concatenation.
   A document takes a buffer and an indentation, has side effects on the buffer
   and returns a new indentation. The indentation argument indicates the level
   of indentation to be used if a new line has to be started (because of what is
   already in the buffer) *)
type doc = Buffer.t -> int -> int

let rec printTree (printer : int -> 'a -> doc) (tree : 'a) : string =
    let buffer_init_size = 64 (* you may want to change this *)
    in let buffer = Buffer.create buffer_init_size
    in
        let _ = printer 0 tree buffer 0 in (* discard return value *)
        Buffer.contents buffer

let indent_width = 2

let spaces (i: int) : string = if i > 0 then String.make i ' ' else ""
let indent (i: int) : string = "\n" ^ spaces i

(* To avoid dependency on package extlib, which has
   Extlib.ExtChar.Char.is_whitespace, we employ the following awkward
   way to check a character for whitespace.
   Note: String.trim exists in the core libraries since Ocaml 4.00. *)
let isWhiteSpace (c: char) : bool = String.trim (String.make 1 c) = ""

(* this render function is written for C-style languages, you may want to change it *)
let render (s : string) : doc = fun buf i ->
    (* invariant: last char of the buffer is never whitespace *)
    let n = Buffer.length buf in
    let last = if n = 0 then None else Some (Buffer.nth buf (n-1)) in
    let newindent = match s with
        "{" -> i + indent_width
      | "}" -> i - indent_width
      | _ -> i in
    let whitespace = match last with
        None -> ""
      | Some '}' -> (match s with
            ";" -> ""
          | _ -> indent newindent)
      | (Some '{') | (Some ';') -> if s = "}" then indent newindent else indent i
      | (Some '[') | (Some '(') -> ""
      | Some c -> if isWhiteSpace c then "" else (match s with
             ";" | "," | ")" | "]" -> ""
           | "{" -> indent i
           | "}" -> indent newindent
           | _ -> if String.trim s = "" then "" else " ") in
    Buffer.add_string buf whitespace;
    Buffer.add_string buf s;
    newindent

let emptyDoc : doc = fun buf i -> i

let concatD (ds : doc list) : doc = fun buf i ->
    List.fold_left (fun accIndent elemDoc -> elemDoc buf accIndent) (emptyDoc buf i) ds

let parenth (d:doc) : doc = concatD [render "("; d; render ")"]

let prPrec (i:int) (j:int) (d:doc) : doc = if j<i then parenth d else d


let prtChar (_:int) (c:char) : doc = render ("'" ^ Char.escaped c ^ "'")



let prtInt (_:int) (i:int) : doc = render (string_of_int i)
let rec prtIntListBNFC i es : doc = match (i, es) with
    (_,[]) -> (concatD [])
  | (_,[x]) -> (concatD [prtInt 0 x])
  | (_,x::xs) -> (concatD [prtInt 0 x ; render ";" ; prtIntListBNFC 0 xs])


let prtFloat (_:int) (f:float) : doc = render (sprintf "%.15g" f)



let prtString (_:int) (s:string) : doc = render ("\"" ^ String.escaped s ^ "\"")
let rec prtStringListBNFC i es : doc = match (i, es) with
    (_,[]) -> (concatD [])
  | (_,[x]) -> (concatD [prtString 0 x])
  | (_,x::xs) -> (concatD [prtString 0 x ; render ";" ; prtStringListBNFC 0 xs])



let prtBinary _ (AbsSemantics.Binary i) : doc = render i



let rec prtStmtLines (i:int) (e : AbsSemantics.stmtLines) : doc = match e with
       AbsSemantics.StmtLinesStmt stmt -> prPrec i 0 (concatD [prtStmt 0 stmt])

and prtStmtLinesListBNFC i es : doc = match (i, es) with
    (_,[]) -> (concatD [])
  | (_,x::xs) -> (concatD [prtStmtLines 0 x ; prtStmtLinesListBNFC 0 xs])
and prtStmt (i:int) (e : AbsSemantics.stmt) : doc = match e with
       AbsSemantics.Stmt_Assign (lexpr, expr) -> prPrec i 0 (concatD [render "Stmt_Assign" ; render "(" ; prtLexpr 0 lexpr ; render "," ; prtExpr 0 expr ; render ")"])
  |    AbsSemantics.Stmt_ConstDecl (type_, string, expr) -> prPrec i 0 (concatD [render "Stmt_ConstDecl" ; render "(" ; prtTypeT 0 type_ ; render "," ; prtString 0 string ; render "," ; prtExpr 0 expr ; render ")"])
  |    AbsSemantics.Stmt_VarDecl (type_, string, expr) -> prPrec i 0 (concatD [render "Stmt_VarDecl" ; render "(" ; prtTypeT 0 type_ ; render "," ; prtString 0 string ; render "," ; prtExpr 0 expr ; render ")"])
  |    AbsSemantics.Stmt_VarDeclsNoInit (type_, strings) -> prPrec i 0 (concatD [render "Stmt_VarDeclsNoInit" ; render "(" ; prtTypeT 0 type_ ; render "," ; render "[" ; prtStringListBNFC 0 strings ; render "]" ; render ")"])
  |    AbsSemantics.Stmt_Assert expr -> prPrec i 0 (concatD [render "Stmt_Assert" ; render "(" ; prtExpr 0 expr ; render ")"])
  |    AbsSemantics.Stmt_Throw string -> prPrec i 0 (concatD [render "Stmt_Throw" ; render "(" ; prtString 0 string ; render ")"])
  |    AbsSemantics.Stmt_TCall (callname, integers, exprs) -> prPrec i 0 (concatD [render "Stmt_TCall" ; render "(" ; prtCallName 0 callname ; render "," ; render "[" ; prtIntListBNFC 0 integers ; render "]" ; render "," ; render "[" ; prtExprListBNFC 0 exprs ; render "]" ; render ")"])
  |    AbsSemantics.Stmt_If (expr, stmts1, stmts2) -> prPrec i 0 (concatD [render "Stmt_If" ; render "(" ; prtExpr 0 expr ; render "," ; render "[" ; prtStmtListBNFC 0 stmts1 ; render "]" ; render "," ; render "[" ; render "]" ; render "," ; render "[" ; prtStmtListBNFC 0 stmts2 ; render "]" ; render ")"])

and prtStmtListBNFC i es : doc = match (i, es) with
    (_,[]) -> (concatD [])
  | (_,[x]) -> (concatD [prtStmt 0 x])
  | (_,x::xs) -> (concatD [prtStmt 0 x ; render ";" ; prtStmtListBNFC 0 xs])
and prtRegTypeSlices (i:int) (e : AbsSemantics.regTypeSlices) : doc = match e with
       AbsSemantics.Slice_HiLo expr -> prPrec i 0 (concatD [render "(" ; render "[" ; render "Slice_HiLo" ; render "(" ; prtExpr 0 expr ; render ","])

and prtRegTypeSlicesListBNFC i es : doc = match (i, es) with
    (_,[]) -> (concatD [])
  | (_,[x]) -> (concatD [prtRegTypeSlices 0 x])
  | (_,x::xs) -> (concatD [prtRegTypeSlices 0 x ; render "," ; prtRegTypeSlicesListBNFC 0 xs])
and prtTypeT (i:int) (e : AbsSemantics.typeT) : doc = match e with
       AbsSemantics.Type_Bits integer -> prPrec i 0 (concatD [render "Type_Bits" ; render "(" ; prtInt 0 integer ; render ")"])
  |    AbsSemantics.Type_Boolean  -> prPrec i 0 (concatD [render "Type_Constructor" ; render "(" ; render "\"boolean\"" ; render ")"])
  |    AbsSemantics.Type_Constructor string -> prPrec i 0 (concatD [render "Type_Constructor" ; render "(" ; prtString 0 string ; render ")"])


and prtLexpr (i:int) (e : AbsSemantics.lexpr) : doc = match e with
       AbsSemantics.Lexpr_KnownVar varname -> prPrec i 0 (concatD [render "LExpr_Var" ; render "(" ; prtVarName 0 varname ; render ")"])
  |    AbsSemantics.Lexpr_LocalVar string -> prPrec i 0 (concatD [render "LExpr_Var" ; render "(" ; prtString 0 string ; render ")"])
  |    AbsSemantics.Lexpr_Field (structname, structfield) -> prPrec i 0 (concatD [render "LExpr_Field" ; render "(" ; render "LExpr_Var" ; render "(" ; prtStructName 0 structname ; render ")" ; render "," ; prtStructField 0 structfield ; render ")"])
  |    AbsSemantics.Lexpr_Array (arrayname, integer) -> prPrec i 0 (concatD [render "LExpr_Array" ; render "(" ; render "LExpr_Var" ; render "(" ; prtArrayName 0 arrayname ; render ")" ; render "," ; prtInt 0 integer ; render ")"])


and prtExpr (i:int) (e : AbsSemantics.expr) : doc = match e with
       AbsSemantics.Expr_True  -> prPrec i 0 (concatD [render "Expr_Var" ; render "(" ; render "\"TRUE\"" ; render ")"])
  |    AbsSemantics.Expr_False  -> prPrec i 0 (concatD [render "Expr_Var" ; render "(" ; render "\"FALSE\"" ; render ")"])
  |    AbsSemantics.Expr_KnownVar varname -> prPrec i 0 (concatD [render "Expr_Var" ; render "(" ; prtVarName 0 varname ; render ")"])
  |    AbsSemantics.Expr_LocalVar string -> prPrec i 0 (concatD [render "Expr_Var" ; render "(" ; prtString 0 string ; render ")"])
  |    AbsSemantics.Expr_Prim (primname, integers, exprs) -> prPrec i 0 (concatD [render "Expr_TApply" ; render "(" ; prtPrimName 0 primname ; render "," ; render "[" ; prtIntListBNFC 0 integers ; render "]" ; render "," ; render "[" ; prtExprListBNFC 0 exprs ; render "]" ; render ")"])
  |    AbsSemantics.Expr_VecPrim (vecprimname, integers, exprs) -> prPrec i 0 (concatD [render "Expr_TApply" ; render "(" ; prtVecPrimName 0 vecprimname ; render "," ; render "[" ; prtIntListBNFC 0 integers ; render "]" ; render "," ; render "[" ; prtExprListBNFC 0 exprs ; render "]" ; render ")"])
  |    AbsSemantics.Expr_Slices (expr, slice) -> prPrec i 0 (concatD [render "Expr_Slices" ; render "(" ; prtExpr 0 expr ; render "," ; render "[" ; prtSlice 0 slice ; render "]" ; render ")"])
  |    AbsSemantics.Expr_Field (structname, structfield) -> prPrec i 0 (concatD [render "Expr_Field" ; render "(" ; render "Expr_Var" ; render "(" ; prtStructName 0 structname ; render ")" ; render "," ; prtStructField 0 structfield ; render ")"])
  |    AbsSemantics.Expr_Array (arrayname, integer) -> prPrec i 0 (concatD [render "Expr_Array" ; render "(" ; render "Expr_Var" ; render "(" ; prtArrayName 0 arrayname ; render ")" ; render "," ; prtInt 0 integer ; render ")"])
  |    AbsSemantics.Expr_LitInt integer -> prPrec i 0 (concatD [prtInt 0 integer])
  |    AbsSemantics.Expr_LitBits binary -> prPrec i 0 (concatD [prtBinary 0 binary])

and prtExprListBNFC i es : doc = match (i, es) with
    (_,[]) -> (concatD [])
  | (_,[x]) -> (concatD [prtExpr 0 x])
  | (_,x::xs) -> (concatD [prtExpr 0 x ; render ";" ; prtExprListBNFC 0 xs])
and prtSlice (i:int) (e : AbsSemantics.slice) : doc = match e with
       AbsSemantics.Slice_LoWd (integer1, integer2) -> prPrec i 0 (concatD [render "Slice_LoWd" ; render "(" ; prtInt 0 integer1 ; render "," ; prtInt 0 integer2 ; render ")"])


and prtVarName (i:int) (e : AbsSemantics.varName) : doc = match e with
       AbsSemantics.Var_PC  -> prPrec i 0 (concatD [render "\"_PC\""])
  |    AbsSemantics.Var_SP_EL0  -> prPrec i 0 (concatD [render "\"SP_EL0\""])
  |    AbsSemantics.Var_FPCR  -> prPrec i 0 (concatD [render "\"FPCR\""])
  |    AbsSemantics.Var_FPSR  -> prPrec i 0 (concatD [render "\"FPSR\""])
  |    AbsSemantics.Var_BTypeCompatible  -> prPrec i 0 (concatD [render "\"BTypeCompatible\""])
  |    AbsSemantics.Var_BranchTaken  -> prPrec i 0 (concatD [render "\"__BranchTaken\""])
  |    AbsSemantics.Var_BTypeNext  -> prPrec i 0 (concatD [render "\"BTypeNext\""])
  |    AbsSemantics.Var_ExclusiveLocal  -> prPrec i 0 (concatD [render "\"__ExclusiveLocal\""])


and prtStructName (i:int) (e : AbsSemantics.structName) : doc = match e with
       AbsSemantics.Struct_Pstate  -> prPrec i 0 (concatD [render "\"PSTATE\""])


and prtStructField (i:int) (e : AbsSemantics.structField) : doc = match e with
       AbsSemantics.Field_N  -> prPrec i 0 (concatD [render "\"N\""])
  |    AbsSemantics.Field_Z  -> prPrec i 0 (concatD [render "\"Z\""])
  |    AbsSemantics.Field_C  -> prPrec i 0 (concatD [render "\"C\""])
  |    AbsSemantics.Field_V  -> prPrec i 0 (concatD [render "\"V\""])
  |    AbsSemantics.Field_A  -> prPrec i 0 (concatD [render "\"A\""])
  |    AbsSemantics.Field_D  -> prPrec i 0 (concatD [render "\"D\""])
  |    AbsSemantics.Field_DIT  -> prPrec i 0 (concatD [render "\"DIT\""])
  |    AbsSemantics.Field_F  -> prPrec i 0 (concatD [render "\"F\""])
  |    AbsSemantics.Field_I  -> prPrec i 0 (concatD [render "\"I\""])
  |    AbsSemantics.Field_PAN  -> prPrec i 0 (concatD [render "\"PAN\""])
  |    AbsSemantics.Field_SP  -> prPrec i 0 (concatD [render "\"SP\""])
  |    AbsSemantics.Field_SSBS  -> prPrec i 0 (concatD [render "\"SSBS\""])
  |    AbsSemantics.Field_TCO  -> prPrec i 0 (concatD [render "\"TCO\""])
  |    AbsSemantics.Field_UAO  -> prPrec i 0 (concatD [render "\"UAO\""])
  |    AbsSemantics.Field_BTYPE  -> prPrec i 0 (concatD [render "\"BTYPE\""])


and prtArrayName (i:int) (e : AbsSemantics.arrayName) : doc = match e with
       AbsSemantics.Array_R  -> prPrec i 0 (concatD [render "\"_R\""])
  |    AbsSemantics.Array_Z  -> prPrec i 0 (concatD [render "\"_Z\""])


and prtCallName (i:int) (e : AbsSemantics.callName) : doc = match e with
       AbsSemantics.Call_Mem_set  -> prPrec i 0 (concatD [render "\"Mem.set.0\""])
  |    AbsSemantics.Call_AtomicStart  -> prPrec i 0 (concatD [render "\"AtomicStart.0\""])
  |    AbsSemantics.Call_AtomicEnd  -> prPrec i 0 (concatD [render "\"AtomicEnd.0\""])
  |    AbsSemantics.Call_Memtag_read  -> prPrec i 0 (concatD [render "\"AArch64.MemTag.read.0\""])
  |    AbsSemantics.Call_Memtag_set  -> prPrec i 0 (concatD [render "\"AArch64.MemTag.set.0\""])


and prtPrimName (i:int) (e : AbsSemantics.primName) : doc = match e with
       AbsSemantics.Prim_Mem_read  -> prPrec i 0 (concatD [render "\"Mem.read.0\""])
  |    AbsSemantics.Prim_and_bool  -> prPrec i 0 (concatD [render "\"and_bool.0\""])
  |    AbsSemantics.Prim_or_bool  -> prPrec i 0 (concatD [render "\"or_bool.0\""])
  |    AbsSemantics.Prim_not_bool  -> prPrec i 0 (concatD [render "\"not_bool.0\""])
  |    AbsSemantics.Prim_cvt_bits_uint  -> prPrec i 0 (concatD [render "\"cvt_bits_uint.0\""])
  |    AbsSemantics.Prim_eq_bits  -> prPrec i 0 (concatD [render "\"eq_bits.0\""])
  |    AbsSemantics.Prim_ne_bits  -> prPrec i 0 (concatD [render "\"ne_bits.0\""])
  |    AbsSemantics.Prim_not_bits  -> prPrec i 0 (concatD [render "\"not_bits.0\""])
  |    AbsSemantics.Prim_cvt_bool_bv  -> prPrec i 0 (concatD [render "\"cvt_bool_bv.0\""])
  |    AbsSemantics.Prim_or_bits  -> prPrec i 0 (concatD [render "\"or_bits.0\""])
  |    AbsSemantics.Prim_eor_bits  -> prPrec i 0 (concatD [render "\"eor_bits.0\""])
  |    AbsSemantics.Prim_and_bits  -> prPrec i 0 (concatD [render "\"and_bits.0\""])
  |    AbsSemantics.Prim_add_bits  -> prPrec i 0 (concatD [render "\"add_bits.0\""])
  |    AbsSemantics.Prim_sub_bits  -> prPrec i 0 (concatD [render "\"sub_bits.0\""])
  |    AbsSemantics.Prim_sdiv_bits  -> prPrec i 0 (concatD [render "\"sdiv_bits.0\""])
  |    AbsSemantics.Prim_sle_bits  -> prPrec i 0 (concatD [render "\"sle_bits.0\""])
  |    AbsSemantics.Prim_slt_bits  -> prPrec i 0 (concatD [render "\"slt_bits.0\""])
  |    AbsSemantics.Prim_mul_bits  -> prPrec i 0 (concatD [render "\"mul_bits.0\""])
  |    AbsSemantics.Prim_append_bits  -> prPrec i 0 (concatD [render "\"append_bits.0\""])
  |    AbsSemantics.Prim_lsr_bits  -> prPrec i 0 (concatD [render "\"lsr_bits.0\""])
  |    AbsSemantics.Prim_lsl_bits  -> prPrec i 0 (concatD [render "\"lsl_bits.0\""])
  |    AbsSemantics.Prim_asr_bits  -> prPrec i 0 (concatD [render "\"asr_bits.0\""])
  |    AbsSemantics.Prim_replicate_bits  -> prPrec i 0 (concatD [render "\"replicate_bits.0\""])
  |    AbsSemantics.Prim_ZeroExtend  -> prPrec i 0 (concatD [render "\"ZeroExtend.0\""])
  |    AbsSemantics.Prim_SignExtend  -> prPrec i 0 (concatD [render "\"SignExtend.0\""])
  |    AbsSemantics.Prim_FPCompare  -> prPrec i 0 (concatD [render "\"FPCompare.0\""])
  |    AbsSemantics.Prim_FPCompareEQ  -> prPrec i 0 (concatD [render "\"FPCompareEQ.0\""])
  |    AbsSemantics.Prim_FPCompareGE  -> prPrec i 0 (concatD [render "\"FPCompareGE.0\""])
  |    AbsSemantics.Prim_FPCompareGT  -> prPrec i 0 (concatD [render "\"FPCompareGT.0\""])
  |    AbsSemantics.Prim_FPAdd  -> prPrec i 0 (concatD [render "\"FPAdd.0\""])
  |    AbsSemantics.Prim_FPSub  -> prPrec i 0 (concatD [render "\"FPSub.0\""])
  |    AbsSemantics.Prim_FPMulAdd  -> prPrec i 0 (concatD [render "\"FPMulAdd.0\""])
  |    AbsSemantics.Prim_FPMulAddH  -> prPrec i 0 (concatD [render "\"FPMulAddH.0\""])
  |    AbsSemantics.Prim_FPMulX  -> prPrec i 0 (concatD [render "\"FPMulX.0\""])
  |    AbsSemantics.Prim_FPMul  -> prPrec i 0 (concatD [render "\"FPMul.0\""])
  |    AbsSemantics.Prim_FPDiv  -> prPrec i 0 (concatD [render "\"FPDiv.0\""])
  |    AbsSemantics.Prim_FPMin  -> prPrec i 0 (concatD [render "\"FPMin.0\""])
  |    AbsSemantics.Prim_FPMinNum  -> prPrec i 0 (concatD [render "\"FPMinNum.0\""])
  |    AbsSemantics.Prim_FPMax  -> prPrec i 0 (concatD [render "\"FPMax.0\""])
  |    AbsSemantics.Prim_FPMaxNum  -> prPrec i 0 (concatD [render "\"FPMaxNum.0\""])
  |    AbsSemantics.Prim_FPRecpX  -> prPrec i 0 (concatD [render "\"FPRecpX.0\""])
  |    AbsSemantics.Prim_FPSqrt  -> prPrec i 0 (concatD [render "\"FPSqrt.0\""])
  |    AbsSemantics.Prim_FPRecipEstimate  -> prPrec i 0 (concatD [render "\"FPRecipEstimate.0\""])
  |    AbsSemantics.Prim_UnsignedRSqrtEstimate  -> prPrec i 0 (concatD [render "\"UnsignedRSqrtEstimate.0\""])
  |    AbsSemantics.Prim_FPRSqrtEstimate  -> prPrec i 0 (concatD [render "\"FPRSqrtEstimate.0\""])
  |    AbsSemantics.Prim_BFAdd  -> prPrec i 0 (concatD [render "\"BFAdd.0\""])
  |    AbsSemantics.Prim_BFMul  -> prPrec i 0 (concatD [render "\"BFMul.0\""])
  |    AbsSemantics.Prim_FPConvertBF  -> prPrec i 0 (concatD [render "\"FPConvertBF.0\""])
  |    AbsSemantics.Prim_FPRecipStepFused  -> prPrec i 0 (concatD [render "\"FPRecipStepFused.0\""])
  |    AbsSemantics.Prim_FPRSqrtStepFused  -> prPrec i 0 (concatD [render "\"FPRSqrtStepFused.0\""])
  |    AbsSemantics.Prim_FPToFixed  -> prPrec i 0 (concatD [render "\"FPToFixed.0\""])
  |    AbsSemantics.Prim_FixedToFP  -> prPrec i 0 (concatD [render "\"FixedToFP.0\""])
  |    AbsSemantics.Prim_FPConvert  -> prPrec i 0 (concatD [render "\"FPConvert.0\""])
  |    AbsSemantics.Prim_FPRoundInt  -> prPrec i 0 (concatD [render "\"FPRoundInt.0\""])
  |    AbsSemantics.Prim_FPRoundIntN  -> prPrec i 0 (concatD [render "\"FPRoundIntN.0\""])
  |    AbsSemantics.Prim_FPToFixedJS_impl  -> prPrec i 0 (concatD [render "\"FPToFixedJS_impl.0\""])


and prtVecPrimName (i:int) (e : AbsSemantics.vecPrimName) : doc = match e with
       AbsSemantics.VecPrim_Elem_set  -> prPrec i 0 (concatD [render "\"Elem.set.0\""])
  |    AbsSemantics.VecPrim_Elem_read  -> prPrec i 0 (concatD [render "\"Elem.read.0\""])
  |    AbsSemantics.VecPrim_add_vec  -> prPrec i 0 (concatD [render "\"add_vec.0\""])
  |    AbsSemantics.VecPrim_sub_vec  -> prPrec i 0 (concatD [render "\"sub_vec.0\""])
  |    AbsSemantics.VecPrim_mul_vec  -> prPrec i 0 (concatD [render "\"mul_vec.0\""])
  |    AbsSemantics.VecPrim_sdiv_vec  -> prPrec i 0 (concatD [render "\"sdiv_vec.0\""])
  |    AbsSemantics.VecPrim_lsr_vec  -> prPrec i 0 (concatD [render "\"lsr_vec.0\""])
  |    AbsSemantics.VecPrim_asr_vec  -> prPrec i 0 (concatD [render "\"asr_vec.0\""])
  |    AbsSemantics.VecPrim_lsl_vec  -> prPrec i 0 (concatD [render "\"lsl_vec.0\""])
  |    AbsSemantics.VecPrim_ite_vec  -> prPrec i 0 (concatD [render "\"ite_vec.0\""])
  |    AbsSemantics.VecPrim_sle_vec  -> prPrec i 0 (concatD [render "\"sle_vec.0\""])
  |    AbsSemantics.VecPrim_slt_vec  -> prPrec i 0 (concatD [render "\"slt_vec.0\""])
  |    AbsSemantics.VecPrim_eq_vec  -> prPrec i 0 (concatD [render "\"eq_vec.0\""])
  |    AbsSemantics.VecPrim_zcast_vec  -> prPrec i 0 (concatD [render "\"zcast_vec.0\""])
  |    AbsSemantics.VecPrim_scast_vec  -> prPrec i 0 (concatD [render "\"scast_vec.0\""])
  |    AbsSemantics.VecPrim_trunc_vec  -> prPrec i 0 (concatD [render "\"trunc_vec.0\""])
  |    AbsSemantics.VecPrim_select_vec  -> prPrec i 0 (concatD [render "\"select_vec.0\""])
  |    AbsSemantics.VecPrim_shuffle_vec  -> prPrec i 0 (concatD [render "\"shuffle_vec.0\""])
  |    AbsSemantics.VecPrim_reduce_add  -> prPrec i 0 (concatD [render "\"reduce_add.0\""])



