(* File generated by the BNF Converter (bnfc 2.9.5). *)

(* show functions *)

(* use string buffers for efficient string concatenations *)
type showable = Buffer.t -> unit

let show (s : showable) : string =
    let init_size = 16 in (* you may want to adjust this *)
    let b = Buffer.create init_size in
    s b;
    Buffer.contents b

let emptyS : showable = fun buf -> ()

let c2s (c:char) : showable = fun buf -> Buffer.add_char buf c
let s2s (s:string) : showable = fun buf -> Buffer.add_string buf s

let ( >> ) (s1 : showable) (s2 : showable) : showable = fun buf -> s1 buf; s2 buf

let showChar (c:char) : showable = fun buf ->
    Buffer.add_string buf ("'" ^ Char.escaped c ^ "'")

let showString (s:string) : showable = fun buf ->
    Buffer.add_string buf ("\"" ^ String.escaped s ^ "\"")

let showList (showFun : 'a -> showable) (xs : 'a list) : showable = fun buf ->
    let rec f ys = match ys with
        [] -> ()
      | [y] -> showFun y buf
      | y::ys -> showFun y buf; Buffer.add_string buf "; "; f ys
    in
        Buffer.add_char buf '[';
        f xs;
        Buffer.add_char buf ']'


let showInt (i:int) : showable = s2s (string_of_int i)
let showFloat (f:float) : showable = s2s (string_of_float f)

let rec showBinary (AbsSemantics.Binary i) : showable = s2s "Binary " >> showString i

let rec showStmtLines (e : AbsSemantics.stmtLines) : showable = match e with
       AbsSemantics.StmtLinesStmt stmt -> s2s "StmtLinesStmt" >> c2s ' ' >> c2s '(' >> showStmt stmt >> c2s ')'


and showStmt (e : AbsSemantics.stmt) : showable = match e with
       AbsSemantics.Stmt_Assign (lexpr, expr) -> s2s "Stmt_Assign" >> c2s ' ' >> c2s '(' >> showLexpr lexpr  >> s2s ", " >>  showExpr expr >> c2s ')'
  |    AbsSemantics.Stmt_ConstDecl (type', string, expr) -> s2s "Stmt_ConstDecl" >> c2s ' ' >> c2s '(' >> showTypeT type'  >> s2s ", " >>  showString string  >> s2s ", " >>  showExpr expr >> c2s ')'
  |    AbsSemantics.Stmt_VarDecl (type', string, expr) -> s2s "Stmt_VarDecl" >> c2s ' ' >> c2s '(' >> showTypeT type'  >> s2s ", " >>  showString string  >> s2s ", " >>  showExpr expr >> c2s ')'
  |    AbsSemantics.Stmt_VarDeclsNoInit (type', strings) -> s2s "Stmt_VarDeclsNoInit" >> c2s ' ' >> c2s '(' >> showTypeT type'  >> s2s ", " >>  showList showString strings >> c2s ')'
  |    AbsSemantics.Stmt_Assert expr -> s2s "Stmt_Assert" >> c2s ' ' >> c2s '(' >> showExpr expr >> c2s ')'
  |    AbsSemantics.Stmt_Throw string -> s2s "Stmt_Throw" >> c2s ' ' >> c2s '(' >> showString string >> c2s ')'
  |    AbsSemantics.Stmt_TCall (callname, integers, exprs) -> s2s "Stmt_TCall" >> c2s ' ' >> c2s '(' >> showCallName callname  >> s2s ", " >>  showList showInt integers  >> s2s ", " >>  showList showExpr exprs >> c2s ')'
  |    AbsSemantics.Stmt_If (expr, stmts0, stmts) -> s2s "Stmt_If" >> c2s ' ' >> c2s '(' >> showExpr expr  >> s2s ", " >>  showList showStmt stmts0  >> s2s ", " >>  showList showStmt stmts >> c2s ')'


and showRegTypeSlices (e : AbsSemantics.regTypeSlices) : showable = match e with
       AbsSemantics.Slice_HiLo expr -> s2s "Slice_HiLo" >> c2s ' ' >> c2s '(' >> showExpr expr >> c2s ')'


and showTypeT (e : AbsSemantics.typeT) : showable = match e with
       AbsSemantics.Type_Bits integer -> s2s "Type_Bits" >> c2s ' ' >> c2s '(' >> showInt integer >> c2s ')'
  |    AbsSemantics.Type_Boolean  -> s2s "Type_Boolean"
  |    AbsSemantics.Type_Constructor string -> s2s "Type_Constructor" >> c2s ' ' >> c2s '(' >> showString string >> c2s ')'


and showLexpr (e : AbsSemantics.lexpr) : showable = match e with
       AbsSemantics.Lexpr_KnownVar varname -> s2s "Lexpr_KnownVar" >> c2s ' ' >> c2s '(' >> showVarName varname >> c2s ')'
  |    AbsSemantics.Lexpr_LocalVar string -> s2s "Lexpr_LocalVar" >> c2s ' ' >> c2s '(' >> showString string >> c2s ')'
  |    AbsSemantics.Lexpr_Field (structname, structfield) -> s2s "Lexpr_Field" >> c2s ' ' >> c2s '(' >> showStructName structname  >> s2s ", " >>  showStructField structfield >> c2s ')'
  |    AbsSemantics.Lexpr_Array (arrayname, integer) -> s2s "Lexpr_Array" >> c2s ' ' >> c2s '(' >> showArrayName arrayname  >> s2s ", " >>  showInt integer >> c2s ')'


and showExpr (e : AbsSemantics.expr) : showable = match e with
       AbsSemantics.Expr_True  -> s2s "Expr_True"
  |    AbsSemantics.Expr_False  -> s2s "Expr_False"
  |    AbsSemantics.Expr_KnownVar varname -> s2s "Expr_KnownVar" >> c2s ' ' >> c2s '(' >> showVarName varname >> c2s ')'
  |    AbsSemantics.Expr_LocalVar string -> s2s "Expr_LocalVar" >> c2s ' ' >> c2s '(' >> showString string >> c2s ')'
  |    AbsSemantics.Expr_Prim (primname, integers, exprs) -> s2s "Expr_Prim" >> c2s ' ' >> c2s '(' >> showPrimName primname  >> s2s ", " >>  showList showInt integers  >> s2s ", " >>  showList showExpr exprs >> c2s ')'
  |    AbsSemantics.Expr_VecPrim (vecprimname, integers, exprs) -> s2s "Expr_VecPrim" >> c2s ' ' >> c2s '(' >> showVecPrimName vecprimname  >> s2s ", " >>  showList showInt integers  >> s2s ", " >>  showList showExpr exprs >> c2s ')'
  |    AbsSemantics.Expr_Slices (expr, slice) -> s2s "Expr_Slices" >> c2s ' ' >> c2s '(' >> showExpr expr  >> s2s ", " >>  showSlice slice >> c2s ')'
  |    AbsSemantics.Expr_Field (structname, structfield) -> s2s "Expr_Field" >> c2s ' ' >> c2s '(' >> showStructName structname  >> s2s ", " >>  showStructField structfield >> c2s ')'
  |    AbsSemantics.Expr_Array (arrayname, integer) -> s2s "Expr_Array" >> c2s ' ' >> c2s '(' >> showArrayName arrayname  >> s2s ", " >>  showInt integer >> c2s ')'
  |    AbsSemantics.Expr_LitInt integer -> s2s "Expr_LitInt" >> c2s ' ' >> c2s '(' >> showInt integer >> c2s ')'
  |    AbsSemantics.Expr_LitBits binary -> s2s "Expr_LitBits" >> c2s ' ' >> c2s '(' >> showBinary binary >> c2s ')'


and showSlice (e : AbsSemantics.slice) : showable = match e with
       AbsSemantics.Slice_LoWd (integer0, integer) -> s2s "Slice_LoWd" >> c2s ' ' >> c2s '(' >> showInt integer0  >> s2s ", " >>  showInt integer >> c2s ')'


and showVarName (e : AbsSemantics.varName) : showable = match e with
       AbsSemantics.Var_PC  -> s2s "Var_PC"
  |    AbsSemantics.Var_SP_EL0  -> s2s "Var_SP_EL0"
  |    AbsSemantics.Var_FPCR  -> s2s "Var_FPCR"
  |    AbsSemantics.Var_FPSR  -> s2s "Var_FPSR"
  |    AbsSemantics.Var_BTypeCompatible  -> s2s "Var_BTypeCompatible"
  |    AbsSemantics.Var_BranchTaken  -> s2s "Var_BranchTaken"
  |    AbsSemantics.Var_BTypeNext  -> s2s "Var_BTypeNext"
  |    AbsSemantics.Var_ExclusiveLocal  -> s2s "Var_ExclusiveLocal"


and showStructName (e : AbsSemantics.structName) : showable = match e with
       AbsSemantics.Struct_Pstate  -> s2s "Struct_Pstate"


and showStructField (e : AbsSemantics.structField) : showable = match e with
       AbsSemantics.Field_N  -> s2s "Field_N"
  |    AbsSemantics.Field_Z  -> s2s "Field_Z"
  |    AbsSemantics.Field_C  -> s2s "Field_C"
  |    AbsSemantics.Field_V  -> s2s "Field_V"
  |    AbsSemantics.Field_A  -> s2s "Field_A"
  |    AbsSemantics.Field_D  -> s2s "Field_D"
  |    AbsSemantics.Field_DIT  -> s2s "Field_DIT"
  |    AbsSemantics.Field_F  -> s2s "Field_F"
  |    AbsSemantics.Field_I  -> s2s "Field_I"
  |    AbsSemantics.Field_PAN  -> s2s "Field_PAN"
  |    AbsSemantics.Field_SP  -> s2s "Field_SP"
  |    AbsSemantics.Field_SSBS  -> s2s "Field_SSBS"
  |    AbsSemantics.Field_TCO  -> s2s "Field_TCO"
  |    AbsSemantics.Field_UAO  -> s2s "Field_UAO"
  |    AbsSemantics.Field_BTYPE  -> s2s "Field_BTYPE"


and showArrayName (e : AbsSemantics.arrayName) : showable = match e with
       AbsSemantics.Array_R  -> s2s "Array_R"
  |    AbsSemantics.Array_Z  -> s2s "Array_Z"


and showCallName (e : AbsSemantics.callName) : showable = match e with
       AbsSemantics.Call_Mem_set  -> s2s "Call_Mem_set"
  |    AbsSemantics.Call_AtomicStart  -> s2s "Call_AtomicStart"
  |    AbsSemantics.Call_AtomicEnd  -> s2s "Call_AtomicEnd"
  |    AbsSemantics.Call_Memtag_read  -> s2s "Call_Memtag_read"
  |    AbsSemantics.Call_Memtag_set  -> s2s "Call_Memtag_set"


and showPrimName (e : AbsSemantics.primName) : showable = match e with
       AbsSemantics.Prim_Mem_read  -> s2s "Prim_Mem_read"
  |    AbsSemantics.Prim_and_bool  -> s2s "Prim_and_bool"
  |    AbsSemantics.Prim_or_bool  -> s2s "Prim_or_bool"
  |    AbsSemantics.Prim_not_bool  -> s2s "Prim_not_bool"
  |    AbsSemantics.Prim_cvt_bits_uint  -> s2s "Prim_cvt_bits_uint"
  |    AbsSemantics.Prim_eq_bits  -> s2s "Prim_eq_bits"
  |    AbsSemantics.Prim_ne_bits  -> s2s "Prim_ne_bits"
  |    AbsSemantics.Prim_not_bits  -> s2s "Prim_not_bits"
  |    AbsSemantics.Prim_cvt_bool_bv  -> s2s "Prim_cvt_bool_bv"
  |    AbsSemantics.Prim_or_bits  -> s2s "Prim_or_bits"
  |    AbsSemantics.Prim_eor_bits  -> s2s "Prim_eor_bits"
  |    AbsSemantics.Prim_and_bits  -> s2s "Prim_and_bits"
  |    AbsSemantics.Prim_add_bits  -> s2s "Prim_add_bits"
  |    AbsSemantics.Prim_sub_bits  -> s2s "Prim_sub_bits"
  |    AbsSemantics.Prim_sdiv_bits  -> s2s "Prim_sdiv_bits"
  |    AbsSemantics.Prim_sle_bits  -> s2s "Prim_sle_bits"
  |    AbsSemantics.Prim_slt_bits  -> s2s "Prim_slt_bits"
  |    AbsSemantics.Prim_mul_bits  -> s2s "Prim_mul_bits"
  |    AbsSemantics.Prim_append_bits  -> s2s "Prim_append_bits"
  |    AbsSemantics.Prim_lsr_bits  -> s2s "Prim_lsr_bits"
  |    AbsSemantics.Prim_lsl_bits  -> s2s "Prim_lsl_bits"
  |    AbsSemantics.Prim_asr_bits  -> s2s "Prim_asr_bits"
  |    AbsSemantics.Prim_replicate_bits  -> s2s "Prim_replicate_bits"
  |    AbsSemantics.Prim_ZeroExtend  -> s2s "Prim_ZeroExtend"
  |    AbsSemantics.Prim_SignExtend  -> s2s "Prim_SignExtend"
  |    AbsSemantics.Prim_FPCompare  -> s2s "Prim_FPCompare"
  |    AbsSemantics.Prim_FPCompareEQ  -> s2s "Prim_FPCompareEQ"
  |    AbsSemantics.Prim_FPCompareGE  -> s2s "Prim_FPCompareGE"
  |    AbsSemantics.Prim_FPCompareGT  -> s2s "Prim_FPCompareGT"
  |    AbsSemantics.Prim_FPAdd  -> s2s "Prim_FPAdd"
  |    AbsSemantics.Prim_FPSub  -> s2s "Prim_FPSub"
  |    AbsSemantics.Prim_FPMulAdd  -> s2s "Prim_FPMulAdd"
  |    AbsSemantics.Prim_FPMulAddH  -> s2s "Prim_FPMulAddH"
  |    AbsSemantics.Prim_FPMulX  -> s2s "Prim_FPMulX"
  |    AbsSemantics.Prim_FPMul  -> s2s "Prim_FPMul"
  |    AbsSemantics.Prim_FPDiv  -> s2s "Prim_FPDiv"
  |    AbsSemantics.Prim_FPMin  -> s2s "Prim_FPMin"
  |    AbsSemantics.Prim_FPMinNum  -> s2s "Prim_FPMinNum"
  |    AbsSemantics.Prim_FPMax  -> s2s "Prim_FPMax"
  |    AbsSemantics.Prim_FPMaxNum  -> s2s "Prim_FPMaxNum"
  |    AbsSemantics.Prim_FPRecpX  -> s2s "Prim_FPRecpX"
  |    AbsSemantics.Prim_FPSqrt  -> s2s "Prim_FPSqrt"
  |    AbsSemantics.Prim_FPRecipEstimate  -> s2s "Prim_FPRecipEstimate"
  |    AbsSemantics.Prim_UnsignedRSqrtEstimate  -> s2s "Prim_UnsignedRSqrtEstimate"
  |    AbsSemantics.Prim_FPRSqrtEstimate  -> s2s "Prim_FPRSqrtEstimate"
  |    AbsSemantics.Prim_BFAdd  -> s2s "Prim_BFAdd"
  |    AbsSemantics.Prim_BFMul  -> s2s "Prim_BFMul"
  |    AbsSemantics.Prim_FPConvertBF  -> s2s "Prim_FPConvertBF"
  |    AbsSemantics.Prim_FPRecipStepFused  -> s2s "Prim_FPRecipStepFused"
  |    AbsSemantics.Prim_FPRSqrtStepFused  -> s2s "Prim_FPRSqrtStepFused"
  |    AbsSemantics.Prim_FPToFixed  -> s2s "Prim_FPToFixed"
  |    AbsSemantics.Prim_FixedToFP  -> s2s "Prim_FixedToFP"
  |    AbsSemantics.Prim_FPConvert  -> s2s "Prim_FPConvert"
  |    AbsSemantics.Prim_FPRoundInt  -> s2s "Prim_FPRoundInt"
  |    AbsSemantics.Prim_FPRoundIntN  -> s2s "Prim_FPRoundIntN"
  |    AbsSemantics.Prim_FPToFixedJS_impl  -> s2s "Prim_FPToFixedJS_impl"


and showVecPrimName (e : AbsSemantics.vecPrimName) : showable = match e with
       AbsSemantics.VecPrim_Elem_set  -> s2s "VecPrim_Elem_set"
  |    AbsSemantics.VecPrim_Elem_read  -> s2s "VecPrim_Elem_read"
  |    AbsSemantics.VecPrim_add_vec  -> s2s "VecPrim_add_vec"
  |    AbsSemantics.VecPrim_sub_vec  -> s2s "VecPrim_sub_vec"
  |    AbsSemantics.VecPrim_mul_vec  -> s2s "VecPrim_mul_vec"
  |    AbsSemantics.VecPrim_sdiv_vec  -> s2s "VecPrim_sdiv_vec"
  |    AbsSemantics.VecPrim_lsr_vec  -> s2s "VecPrim_lsr_vec"
  |    AbsSemantics.VecPrim_asr_vec  -> s2s "VecPrim_asr_vec"
  |    AbsSemantics.VecPrim_lsl_vec  -> s2s "VecPrim_lsl_vec"
  |    AbsSemantics.VecPrim_ite_vec  -> s2s "VecPrim_ite_vec"
  |    AbsSemantics.VecPrim_sle_vec  -> s2s "VecPrim_sle_vec"
  |    AbsSemantics.VecPrim_slt_vec  -> s2s "VecPrim_slt_vec"
  |    AbsSemantics.VecPrim_eq_vec  -> s2s "VecPrim_eq_vec"
  |    AbsSemantics.VecPrim_zcast_vec  -> s2s "VecPrim_zcast_vec"
  |    AbsSemantics.VecPrim_scast_vec  -> s2s "VecPrim_scast_vec"
  |    AbsSemantics.VecPrim_trunc_vec  -> s2s "VecPrim_trunc_vec"
  |    AbsSemantics.VecPrim_select_vec  -> s2s "VecPrim_select_vec"
  |    AbsSemantics.VecPrim_shuffle_vec  -> s2s "VecPrim_shuffle_vec"
  |    AbsSemantics.VecPrim_reduce_add  -> s2s "VecPrim_reduce_add"



