(* File generated by the BNF Converter (bnfc 2.9.5). *)

module SkelSemantics = struct

open AbsSemantics

type result = string

let failure x = failwith "Undefined case." (* x discarded *)

let rec transBinary (x : binary) : result = match x with
    Binary string -> failure x


and transStmtLines (x : stmtLines) : result = match x with
    StmtLinesStmt stmt -> failure x


and transStmt (x : stmt) : result = match x with
    Stmt_Assign (lexpr, expr) -> failure x
  | Stmt_ConstDecl (type', string, expr) -> failure x
  | Stmt_VarDecl (type', string, expr) -> failure x
  | Stmt_VarDeclsNoInit (type', strings) -> failure x
  | Stmt_Assert expr -> failure x
  | Stmt_Throw string -> failure x
  | Stmt_TCall (callname, integers, exprs) -> failure x
  | Stmt_If (expr, stmts0, stmts) -> failure x


and transRegTypeSlices (x : regTypeSlices) : result = match x with
    Slice_HiLo expr -> failure x


and transType (x : typeT) : result = match x with
    Type_Bits integer -> failure x
  | Type_Boolean  -> failure x
  | Type_Constructor string -> failure x


and transLexpr (x : lexpr) : result = match x with
    Lexpr_KnownVar varname -> failure x
  | Lexpr_LocalVar string -> failure x
  | Lexpr_Field (structname, structfield) -> failure x
  | Lexpr_Array (arrayname, integer) -> failure x


and transExpr (x : expr) : result = match x with
    Expr_True  -> failure x
  | Expr_False  -> failure x
  | Expr_KnownVar varname -> failure x
  | Expr_LocalVar string -> failure x
  | Expr_Prim (primname, integers, exprs) -> failure x
  | Expr_VecPrim (vecprimname, integers, exprs) -> failure x
  | Expr_Slices (expr, slice) -> failure x
  | Expr_Field (structname, structfield) -> failure x
  | Expr_Array (arrayname, integer) -> failure x
  | Expr_LitInt integer -> failure x
  | Expr_LitBits binary -> failure x


and transSlice (x : slice) : result = match x with
    Slice_LoWd (integer0, integer) -> failure x


and transVarName (x : varName) : result = match x with
    Var_PC  -> failure x
  | Var_SP_EL0  -> failure x
  | Var_FPCR  -> failure x
  | Var_FPSR  -> failure x
  | Var_BTypeCompatible  -> failure x
  | Var_BranchTaken  -> failure x
  | Var_BTypeNext  -> failure x
  | Var_ExclusiveLocal  -> failure x


and transStructName (x : structName) : result = match x with
    Struct_Pstate  -> failure x


and transStructField (x : structField) : result = match x with
    Field_N  -> failure x
  | Field_Z  -> failure x
  | Field_C  -> failure x
  | Field_V  -> failure x
  | Field_A  -> failure x
  | Field_D  -> failure x
  | Field_DIT  -> failure x
  | Field_F  -> failure x
  | Field_I  -> failure x
  | Field_PAN  -> failure x
  | Field_SP  -> failure x
  | Field_SSBS  -> failure x
  | Field_TCO  -> failure x
  | Field_UAO  -> failure x
  | Field_BTYPE  -> failure x


and transArrayName (x : arrayName) : result = match x with
    Array_R  -> failure x
  | Array_Z  -> failure x


and transCallName (x : callName) : result = match x with
    Call_Mem_set  -> failure x
  | Call_AtomicStart  -> failure x
  | Call_AtomicEnd  -> failure x
  | Call_Memtag_read  -> failure x
  | Call_Memtag_set  -> failure x


and transPrimName (x : primName) : result = match x with
    Prim_Mem_read  -> failure x
  | Prim_and_bool  -> failure x
  | Prim_or_bool  -> failure x
  | Prim_not_bool  -> failure x
  | Prim_cvt_bits_uint  -> failure x
  | Prim_eq_bits  -> failure x
  | Prim_ne_bits  -> failure x
  | Prim_not_bits  -> failure x
  | Prim_cvt_bool_bv  -> failure x
  | Prim_or_bits  -> failure x
  | Prim_eor_bits  -> failure x
  | Prim_and_bits  -> failure x
  | Prim_add_bits  -> failure x
  | Prim_sub_bits  -> failure x
  | Prim_sdiv_bits  -> failure x
  | Prim_sle_bits  -> failure x
  | Prim_slt_bits  -> failure x
  | Prim_mul_bits  -> failure x
  | Prim_append_bits  -> failure x
  | Prim_lsr_bits  -> failure x
  | Prim_lsl_bits  -> failure x
  | Prim_asr_bits  -> failure x
  | Prim_replicate_bits  -> failure x
  | Prim_ZeroExtend  -> failure x
  | Prim_SignExtend  -> failure x
  | Prim_FPCompare  -> failure x
  | Prim_FPCompareEQ  -> failure x
  | Prim_FPCompareGE  -> failure x
  | Prim_FPCompareGT  -> failure x
  | Prim_FPAdd  -> failure x
  | Prim_FPSub  -> failure x
  | Prim_FPMulAdd  -> failure x
  | Prim_FPMulAddH  -> failure x
  | Prim_FPMulX  -> failure x
  | Prim_FPMul  -> failure x
  | Prim_FPDiv  -> failure x
  | Prim_FPMin  -> failure x
  | Prim_FPMinNum  -> failure x
  | Prim_FPMax  -> failure x
  | Prim_FPMaxNum  -> failure x
  | Prim_FPRecpX  -> failure x
  | Prim_FPSqrt  -> failure x
  | Prim_FPRecipEstimate  -> failure x
  | Prim_UnsignedRSqrtEstimate  -> failure x
  | Prim_FPRSqrtEstimate  -> failure x
  | Prim_BFAdd  -> failure x
  | Prim_BFMul  -> failure x
  | Prim_FPConvertBF  -> failure x
  | Prim_FPRecipStepFused  -> failure x
  | Prim_FPRSqrtStepFused  -> failure x
  | Prim_FPToFixed  -> failure x
  | Prim_FixedToFP  -> failure x
  | Prim_FPConvert  -> failure x
  | Prim_FPRoundInt  -> failure x
  | Prim_FPRoundIntN  -> failure x
  | Prim_FPToFixedJS_impl  -> failure x


and transVecPrimName (x : vecPrimName) : result = match x with
    VecPrim_Elem_set  -> failure x
  | VecPrim_Elem_read  -> failure x
  | VecPrim_add_vec  -> failure x
  | VecPrim_sub_vec  -> failure x
  | VecPrim_mul_vec  -> failure x
  | VecPrim_sdiv_vec  -> failure x
  | VecPrim_lsr_vec  -> failure x
  | VecPrim_asr_vec  -> failure x
  | VecPrim_lsl_vec  -> failure x
  | VecPrim_ite_vec  -> failure x
  | VecPrim_sle_vec  -> failure x
  | VecPrim_slt_vec  -> failure x
  | VecPrim_eq_vec  -> failure x
  | VecPrim_zcast_vec  -> failure x
  | VecPrim_scast_vec  -> failure x
  | VecPrim_trunc_vec  -> failure x
  | VecPrim_select_vec  -> failure x
  | VecPrim_shuffle_vec  -> failure x
  | VecPrim_reduce_add  -> failure x



end
